version: "3"
services:
  nginx:
    build:
      context: .
    ports:
     - 443:443
    networks:
     - web
  testssl:
    build:
      context: .
      dockerfile: Dockerfile.testssl
    command: -p --poodle --logjam --beast nginx:443
    networks:
     - web
    depends_on:
     - nginx
networks:
  web:
    external: false
